import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding drinks data...');
  await prisma.drink.deleteMany();

  const drinks = [
    // 스파클링 와인 (15개)
    {
      name: 'Dom Pérignon Champagne',
      type: 'sparkling',
      description: '최고급 샴페인의 정수, 우아한 기포감',
      tastingNotes: ['fruity', 'elegant', 'light'],
      image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=400&h=600&fit=crop',
      price: '₩350,000',
      foodPairings: ['seafood', 'pasta', 'cheese', 'dessert'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSHWC9'
    },
    {
      name: 'Moët & Chandon Brut',
      type: 'sparkling',
      description: '세계적으로 유명한 샴페인',
      tastingNotes: ['fruity', 'elegant', 'light'],
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      price: '₩85,000',
      foodPairings: ['seafood', 'pasta', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSHZaP'
    },
    {
      name: 'Veuve Clicquot Yellow Label',
      type: 'sparkling',
      description: '상징적인 옐로우 라벨 샴페인',
      tastingNotes: ['fruity', 'elegant', 'medium'],
      image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?w=400&h=600&fit=crop',
      price: '₩95,000',
      foodPairings: ['seafood', 'cheese', 'dessert'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSH5ti'
    },
    {
      name: 'Prosecco Superiore DOCG',
      type: 'sparkling',
      description: '이탈리아의 상쾌한 스파클링',
      tastingNotes: ['fruity', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1566754436306-0b4c01c5b7b6?w=400&h=600&fit=crop',
      price: '₩35,000',
      foodPairings: ['seafood', 'pasta', 'light dishes'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSH50p'
    },
    {
      name: 'Cava Reserva',
      type: 'sparkling',
      description: '스페인의 전통 스파클링',
      tastingNotes: ['elegant', 'light', 'crisp'],
      image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=400&h=600&fit=crop',
      price: '₩42,000',
      foodPairings: ['seafood', 'cheese', 'pasta'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSH6lB'
    },
    {
      name: 'Champagne Rosé',
      type: 'sparkling',
      description: '로맨틱한 핑크빛 샴페인',
      tastingNotes: ['fruity', 'elegant', 'light'],
      image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=600&fit=crop',
      price: '₩120,000',
      foodPairings: ['seafood', 'dessert', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSH6RW'
    },
    {
      name: 'Franciacorta Brut',
      type: 'sparkling',
      description: '이탈리아 최고급 스파클링',
      tastingNotes: ['elegant', 'complex', 'medium'],
      image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=400&h=600&fit=crop',
      price: '₩68,000',
      foodPairings: ['seafood', 'pasta', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSH7Dp'
    },
    {
      name: 'Crémant de Bourgogne',
      type: 'sparkling',
      description: '부르고뉴의 우아한 스파클링',
      tastingNotes: ['elegant', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1598524722956-30b0c5b8c7ae?w=400&h=600&fit=crop',
      price: '₩45,000',
      foodPairings: ['seafood', 'cheese', 'light dishes'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSH7Zw'
    },
    {
      name: 'Asti Spumante',
      type: 'sparkling',
      description: '달콤한 이탈리아 스파클링',
      tastingNotes: ['sweet', 'fruity', 'light'],
      image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=600&fit=crop',
      price: '₩28,000',
      foodPairings: ['dessert', 'cheese', 'light dishes'],
      occasions: ['gathering', 'date'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIbxU'
    },
    {
      name: 'Lambrusco Rosso',
      type: 'sparkling',
      description: '이탈리아의 레드 스파클링',
      tastingNotes: ['fruity', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=600&fit=crop',
      price: '₩32,000',
      foodPairings: ['pasta', 'meat', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIa8f'
    },
    {
      name: 'Sekt Riesling',
      type: 'sparkling',
      description: '독일의 프리미엄 스파클링',
      tastingNotes: ['crisp', 'elegant', 'light'],
      image: 'https://images.unsplash.com/photo-1585553616435-2dc0a54e271d?w=400&h=600&fit=crop',
      price: '₩38,000',
      foodPairings: ['seafood', 'cheese', 'light dishes'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIcdz'
    },
    {
      name: 'Blanc de Blancs Champagne',
      type: 'sparkling',
      description: '샤르도네 100% 샴페인',
      tastingNotes: ['elegant', 'complex', 'light'],
      image: 'https://images.unsplash.com/photo-1560148489-8d4b61c5e963?w=400&h=600&fit=crop',
      price: '₩150,000',
      foodPairings: ['seafood', 'cheese', 'light dishes'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIcD9'
    },
    {
      name: 'English Sparkling Wine',
      type: 'sparkling',
      description: '영국의 떠오르는 스파클링',
      tastingNotes: ['elegant', 'crisp', 'light'],
      image: 'https://images.unsplash.com/photo-1596285388606-b3d3e5d39f26?w=400&h=600&fit=crop',
      price: '₩72,000',
      foodPairings: ['seafood', 'cheese', 'dessert'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIc5i'
    },
    {
      name: 'Champagne Blanc de Noirs',
      type: 'sparkling',
      description: '피노 누아로 만든 샴페인',
      tastingNotes: ['bold', 'elegant', 'medium'],
      image: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=400&h=600&fit=crop',
      price: '₩135,000',
      foodPairings: ['meat', 'cheese', 'pasta'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIdmX'
    },
    {
      name: 'Crémant d\'Alsace',
      type: 'sparkling',
      description: '알자스의 섬세한 스파클링',
      tastingNotes: ['elegant', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1597329428431-e3a0c7b0f3f3?w=400&h=600&fit=crop',
      price: '₩48,000',
      foodPairings: ['seafood', 'cheese', 'light dishes'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSId1D'
    },
    // 레드 와인 (30개)
    {
      name: 'Château Margaux',
      type: 'red wine',
      description: '보르도 최고급 와인',
      tastingNotes: ['complex', 'elegant', 'heavy'],
      image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=400&h=600&fit=crop',
      price: '₩850,000',
      foodPairings: ['meat', 'steak', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIfox'
    },
    {
      name: 'Penfolds Grange',
      type: 'red wine',
      description: '호주의 아이콘 와인',
      tastingNotes: ['bold', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      price: '₩650,000',
      foodPairings: ['meat', 'steak', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIfK1'
    },
    {
      name: 'Barolo DOCG',
      type: 'red wine',
      description: '이탈리아 와인의 왕',
      tastingNotes: ['bold', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=600&fit=crop',
      price: '₩180,000',
      foodPairings: ['meat', 'truffle', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIgcS'
    },
    {
      name: 'Brunello di Montalcino',
      type: 'red wine',
      description: '토스카나의 명품 와인',
      tastingNotes: ['elegant', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=400&h=600&fit=crop',
      price: '₩150,000',
      foodPairings: ['meat', 'pasta', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIgKM'
    },
    {
      name: 'Amarone della Valpolicella',
      type: 'red wine',
      description: '농축된 풍미의 이탈리아 와인',
      tastingNotes: ['rich', 'bold', 'heavy'],
      image: 'https://images.unsplash.com/photo-1598524722956-30b0c5b8c7ae?w=400&h=600&fit=crop',
      price: '₩120,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['date', 'solo-drinking'],
      tastes: ['sweet', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIg8b'
    },
    {
      name: 'Châteauneuf-du-Pape',
      type: 'red wine',
      description: '론 밸리의 강력한 와인',
      tastingNotes: ['bold', 'spicy', 'heavy'],
      image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=600&fit=crop',
      price: '₩95,000',
      foodPairings: ['meat', 'stew', 'cheese'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIhzS'
    },
    {
      name: 'Rioja Gran Reserva',
      type: 'red wine',
      description: '스페인의 전통 숙성 와인',
      tastingNotes: ['elegant', 'smooth', 'medium'],
      image: 'https://images.unsplash.com/photo-1560148489-8d4b61c5e963?w=400&h=600&fit=crop',
      price: '₩85,000',
      foodPairings: ['meat', 'tapas', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIhRy'
    },
    {
      name: 'Pinot Noir Burgundy',
      type: 'red wine',
      description: '부르고뉴의 우아한 피노 누아',
      tastingNotes: ['elegant', 'fruity', 'medium'],
      image: 'https://images.unsplash.com/photo-1596285388606-b3d3e5d39f26?w=400&h=600&fit=crop',
      price: '₩120,000',
      foodPairings: ['meat', 'fish', 'mushroom'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIieG'
    },
    {
      name: 'Malbec Mendoza',
      type: 'red wine',
      description: '아르헨티나의 대표 와인',
      tastingNotes: ['fruity', 'bold', 'heavy'],
      image: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=400&h=600&fit=crop',
      price: '₩55,000',
      foodPairings: ['meat', 'bbq', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIiD0'
    },
    {
      name: 'Cabernet Sauvignon Napa',
      type: 'red wine',
      description: '나파 밸리의 프리미엄 카베르네',
      tastingNotes: ['bold', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1597329428431-e3a0c7b0f3f3?w=400&h=600&fit=crop',
      price: '₩180,000',
      foodPairings: ['meat', 'steak', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIi8q'
    },
    {
      name: 'Syrah Côtes du Rhône',
      type: 'red wine',
      description: '론 밸리의 시라',
      tastingNotes: ['spicy', 'bold', 'heavy'],
      image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=400&h=600&fit=crop',
      price: '₩48,000',
      foodPairings: ['meat', 'stew', 'cheese'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIjnf'
    },
    {
      name: 'Zinfandel California',
      type: 'red wine',
      description: '캘리포니아의 과일향 와인',
      tastingNotes: ['fruity', 'bold', 'medium'],
      image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?w=400&h=600&fit=crop',
      price: '₩52,000',
      foodPairings: ['meat', 'bbq', 'pizza'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIjNs'
    },
    {
      name: 'Merlot Bordeaux',
      type: 'red wine',
      description: '보르도의 부드러운 메를로',
      tastingNotes: ['smooth', 'fruity', 'medium'],
      image: 'https://images.unsplash.com/photo-1566754436306-0b4c01c5b7b6?w=400&h=600&fit=crop',
      price: '₩68,000',
      foodPairings: ['meat', 'pasta', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIj9v'
    },
    {
      name: 'Sangiovese Chianti Classico',
      type: 'red wine',
      description: '토스카나의 클래식 와인',
      tastingNotes: ['fruity', 'elegant', 'medium'],
      image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=400&h=600&fit=crop',
      price: '₩45,000',
      foodPairings: ['pasta', 'pizza', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIkoS'
    },
    {
      name: 'Tempranillo Ribera del Duero',
      type: 'red wine',
      description: '스페인의 우아한 템프라니요',
      tastingNotes: ['elegant', 'smooth', 'medium'],
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      price: '₩58,000',
      foodPairings: ['meat', 'tapas', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIkCD'
    },
    {
      name: 'Grenache GSM Blend',
      type: 'red wine',
      description: '그르나슈 블렌드 와인',
      tastingNotes: ['fruity', 'spicy', 'medium'],
      image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=600&fit=crop',
      price: '₩42,000',
      foodPairings: ['meat', 'bbq', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIkU2'
    },
    {
      name: 'Nebbiolo Barbaresco',
      type: 'red wine',
      description: '피에몬테의 우아한 와인',
      tastingNotes: ['elegant', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=400&h=600&fit=crop',
      price: '₩135,000',
      foodPairings: ['meat', 'truffle', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIlbQ'
    },
    {
      name: 'Carmenere Chile',
      type: 'red wine',
      description: '칠레의 시그니처 와인',
      tastingNotes: ['fruity', 'smooth', 'medium'],
      image: 'https://images.unsplash.com/photo-1598524722956-30b0c5b8c7ae?w=400&h=600&fit=crop',
      price: '₩38,000',
      foodPairings: ['meat', 'pasta', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIlpa'
    },
    {
      name: 'Shiraz Australia',
      type: 'red wine',
      description: '호주의 강렬한 시라즈',
      tastingNotes: ['bold', 'spicy', 'heavy'],
      image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=600&fit=crop',
      price: '₩48,000',
      foodPairings: ['meat', 'bbq', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSImee'
    },
    {
      name: 'Primitivo Puglia',
      type: 'red wine',
      description: '이탈리아 남부의 풍부한 와인',
      tastingNotes: ['rich', 'fruity', 'heavy'],
      image: 'https://images.unsplash.com/photo-1560148489-8d4b61c5e963?w=400&h=600&fit=crop',
      price: '₩35,000',
      foodPairings: ['meat', 'pasta', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSImDb'
    },
    {
      name: 'Petite Sirah California',
      type: 'red wine',
      description: '캘리포니아의 진한 와인',
      tastingNotes: ['bold', 'rich', 'heavy'],
      image: 'https://images.unsplash.com/photo-1596285388606-b3d3e5d39f26?w=400&h=600&fit=crop',
      price: '₩55,000',
      foodPairings: ['meat', 'steak', 'cheese'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSImWa'
    },
    {
      name: 'Montepulciano d\'Abruzzo',
      type: 'red wine',
      description: '이탈리아의 가성비 와인',
      tastingNotes: ['fruity', 'smooth', 'medium'],
      image: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=400&h=600&fit=crop',
      price: '₩28,000',
      foodPairings: ['pasta', 'pizza', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSInju'
    },
    {
      name: 'Pinotage South Africa',
      type: 'red wine',
      description: '남아공의 독특한 와인',
      tastingNotes: ['bold', 'smoky', 'medium'],
      image: 'https://images.unsplash.com/photo-1597329428431-e3a0c7b0f3f3?w=400&h=600&fit=crop',
      price: '₩42,000',
      foodPairings: ['meat', 'bbq', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSInQR'
    },
    {
      name: 'Côtes du Rhône Villages',
      type: 'red wine',
      description: '론 밸리의 빌리지 와인',
      tastingNotes: ['fruity', 'spicy', 'medium'],
      image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=400&h=600&fit=crop',
      price: '₩38,000',
      foodPairings: ['meat', 'stew', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIrO9'
    },
    {
      name: 'Valpolicella Ripasso',
      type: 'red wine',
      description: '이탈리아의 리파소 기법 와인',
      tastingNotes: ['rich', 'smooth', 'medium'],
      image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?w=400&h=600&fit=crop',
      price: '₩52,000',
      foodPairings: ['meat', 'pasta', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIsbR'
    },
    {
      name: 'Priorat DOCa',
      type: 'red wine',
      description: '스페인의 프리미엄 와인',
      tastingNotes: ['bold', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1566754436306-0b4c01c5b7b6?w=400&h=600&fit=crop',
      price: '₩95,000',
      foodPairings: ['meat', 'steak', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIsvy'
    },
    {
      name: 'Douro Red Portugal',
      type: 'red wine',
      description: '포르투갈의 풍부한 레드',
      tastingNotes: ['rich', 'bold', 'heavy'],
      image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=400&h=600&fit=crop',
      price: '₩45,000',
      foodPairings: ['meat', 'stew', 'cheese'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIs48'
    },
    {
      name: 'Nero d\'Avola Sicily',
      type: 'red wine',
      description: '시칠리아의 대표 와인',
      tastingNotes: ['fruity', 'bold', 'medium'],
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      price: '₩38,000',
      foodPairings: ['pasta', 'pizza', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSItu5'
    },
    {
      name: 'Aglianico Taurasi',
      type: 'red wine',
      description: '남부 이탈리아의 강력한 와인',
      tastingNotes: ['bold', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=600&fit=crop',
      price: '₩68,000',
      foodPairings: ['meat', 'stew', 'cheese'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSItQk'
    },
    {
      name: 'Touriga Nacional Portugal',
      type: 'red wine',
      description: '포르투갈의 고급 품종',
      tastingNotes: ['elegant', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=400&h=600&fit=crop',
      price: '₩58,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['date', 'solo-drinking'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIumM'
    },
    // 화이트 와인 (25개)
    {
      name: 'Chablis Grand Cru',
      type: 'white wine',
      description: '부르고뉴의 미네랄 샤르도네',
      tastingNotes: ['crisp', 'elegant', 'light'],
      image: 'https://images.unsplash.com/photo-1598524722956-30b0c5b8c7ae?w=400&h=600&fit=crop',
      price: '₩120,000',
      foodPairings: ['seafood', 'oyster', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIuJp'
    },
    {
      name: 'Sancerre',
      type: 'white wine',
      description: '루아르의 상쾌한 소비뇽 블랑',
      tastingNotes: ['crisp', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=600&fit=crop',
      price: '₩65,000',
      foodPairings: ['seafood', 'salad', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIu3b'
    },
    {
      name: 'Pouilly-Fuissé',
      type: 'white wine',
      description: '부르고뉴의 풍부한 샤르도네',
      tastingNotes: ['rich', 'smooth', 'medium'],
      image: 'https://images.unsplash.com/photo-1560148489-8d4b61c5e963?w=400&h=600&fit=crop',
      price: '₩75,000',
      foodPairings: ['seafood', 'chicken', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIvna'
    },
    {
      name: 'Riesling Mosel',
      type: 'white wine',
      description: '독일의 우아한 리슬링',
      tastingNotes: ['sweet', 'fruity', 'light'],
      image: 'https://images.unsplash.com/photo-1596285388606-b3d3e5d39f26?w=400&h=600&fit=crop',
      price: '₩55,000',
      foodPairings: ['seafood', 'spicy', 'dessert'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIvTK'
    },
    {
      name: 'Albariño Rías Baixas',
      type: 'white wine',
      description: '스페인의 해산물 와인',
      tastingNotes: ['crisp', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=400&h=600&fit=crop',
      price: '₩48,000',
      foodPairings: ['seafood', 'salad', 'light dishes'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIwes'
    },
    {
      name: 'Grüner Veltliner',
      type: 'white wine',
      description: '오스트리아의 시그니처 와인',
      tastingNotes: ['crisp', 'spicy', 'light'],
      image: 'https://images.unsplash.com/photo-1597329428431-e3a0c7b0f3f3?w=400&h=600&fit=crop',
      price: '₩42,000',
      foodPairings: ['seafood', 'vegetable', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIwBs'
    },
    {
      name: 'Viognier Condrieu',
      type: 'white wine',
      description: '론 밸리의 향긋한 와인',
      tastingNotes: ['floral', 'rich', 'medium'],
      image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=400&h=600&fit=crop',
      price: '₩85,000',
      foodPairings: ['seafood', 'chicken', 'spicy'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIwSt'
    },
    {
      name: 'Gewürztraminer Alsace',
      type: 'white wine',
      description: '알자스의 향긋한 와인',
      tastingNotes: ['floral', 'sweet', 'medium'],
      image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?w=400&h=600&fit=crop',
      price: '₩52,000',
      foodPairings: ['spicy', 'cheese', 'dessert'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIw8h'
    },
    {
      name: 'Pinot Grigio Alto Adige',
      type: 'white wine',
      description: '이탈리아 북부의 상쾌한 와인',
      tastingNotes: ['crisp', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1566754436306-0b4c01c5b7b6?w=400&h=600&fit=crop',
      price: '₩38,000',
      foodPairings: ['seafood', 'salad', 'light dishes'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIxmX'
    },
    {
      name: 'Vermentino Sardinia',
      type: 'white wine',
      description: '사르데냐의 해변 와인',
      tastingNotes: ['fresh', 'crisp', 'light'],
      image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=400&h=600&fit=crop',
      price: '₩42,000',
      foodPairings: ['seafood', 'salad', 'light dishes'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIxEy'
    },
    {
      name: 'Chenin Blanc Loire',
      type: 'white wine',
      description: '루아르의 다재다능한 와인',
      tastingNotes: ['fruity', 'fresh', 'medium'],
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      price: '₩45,000',
      foodPairings: ['seafood', 'chicken', 'cheese'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIxW0'
    },
    {
      name: 'Soave Classico',
      type: 'white wine',
      description: '베네토의 클래식 와인',
      tastingNotes: ['light', 'fresh', 'elegant'],
      image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=600&fit=crop',
      price: '₩32,000',
      foodPairings: ['seafood', 'pasta', 'light dishes'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIyd5'
    },
    {
      name: 'Muscadet Sèvre et Maine',
      type: 'white wine',
      description: '루아르의 미네랄 와인',
      tastingNotes: ['crisp', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1584916201218-f4242ceb4809?w=400&h=600&fit=crop',
      price: '₩28,000',
      foodPairings: ['seafood', 'oyster', 'light dishes'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIyv6'
    },
    {
      name: 'Fiano di Avellino',
      type: 'white wine',
      description: '남부 이탈리아의 고급 화이트',
      tastingNotes: ['rich', 'complex', 'medium'],
      image: 'https://images.unsplash.com/photo-1598524722956-30b0c5b8c7ae?w=400&h=600&fit=crop',
      price: '₩58,000',
      foodPairings: ['seafood', 'pasta', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIyS7'
    },
    {
      name: 'Greco di Tufo',
      type: 'white wine',
      description: '캄파니아의 우아한 와인',
      tastingNotes: ['elegant', 'crisp', 'medium'],
      image: 'https://images.unsplash.com/photo-1586370434639-0fe43b2d32d6?w=400&h=600&fit=crop',
      price: '₩52,000',
      foodPairings: ['seafood', 'chicken', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sour', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIy8u'
    },
    {
      name: 'Verdejo Rueda',
      type: 'white wine',
      description: '스페인의 상쾌한 화이트',
      tastingNotes: ['fresh', 'crisp', 'light'],
      image: 'https://images.unsplash.com/photo-1560148489-8d4b61c5e963?w=400&h=600&fit=crop',
      price: '₩35,000',
      foodPairings: ['seafood', 'salad', 'tapas'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIznB'
    },
    {
      name: 'Torrontés Argentina',
      type: 'white wine',
      description: '아르헨티나의 향긋한 와인',
      tastingNotes: ['floral', 'fruity', 'light'],
      image: 'https://images.unsplash.com/photo-1596285388606-b3d3e5d39f26?w=400&h=600&fit=crop',
      price: '₩38,000',
      foodPairings: ['seafood', 'spicy', 'light dishes'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIzET'
    },
    {
      name: 'Assyrtiko Santorini',
      type: 'white wine',
      description: '그리스의 미네랄 와인',
      tastingNotes: ['crisp', 'mineral', 'light'],
      image: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=400&h=600&fit=crop',
      price: '₩62,000',
      foodPairings: ['seafood', 'salad', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSICzS'
    },
    {
      name: 'Vinho Verde',
      type: 'white wine',
      description: '포르투갈의 청량한 와인',
      tastingNotes: ['light', 'fresh', 'crisp'],
      image: 'https://images.unsplash.com/photo-1597329428431-e3a0c7b0f3f3?w=400&h=600&fit=crop',
      price: '₩25,000',
      foodPairings: ['seafood', 'salad', 'light dishes'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSICSc'
    },
    {
      name: 'Chardonnay Napa Valley',
      type: 'white wine',
      description: '나파의 풍부한 샤르도네',
      tastingNotes: ['rich', 'smooth', 'heavy'],
      image: 'https://images.unsplash.com/photo-1547595628-c61a29f496f0?w=400&h=600&fit=crop',
      price: '₩95,000',
      foodPairings: ['seafood', 'chicken', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIC9d'
    },
    {
      name: 'Sauvignon Blanc Marlborough',
      type: 'white wine',
      description: '뉴질랜드의 상쾌한 와인',
      tastingNotes: ['crisp', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?w=400&h=600&fit=crop',
      price: '₩45,000',
      foodPairings: ['seafood', 'salad', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIDvP'
    },
    {
      name: 'Semillon Hunter Valley',
      type: 'white wine',
      description: '호주의 숙성 가능한 화이트',
      tastingNotes: ['rich', 'complex', 'medium'],
      image: 'https://images.unsplash.com/photo-1566754436306-0b4c01c5b7b6?w=400&h=600&fit=crop',
      price: '₩58,000',
      foodPairings: ['seafood', 'chicken', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIDQi'
    },
    {
      name: 'Pinot Blanc Alsace',
      type: 'white wine',
      description: '알자스의 부드러운 화이트',
      tastingNotes: ['smooth', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1558346490-a72e53ae2d4f?w=400&h=600&fit=crop',
      price: '₩42,000',
      foodPairings: ['seafood', 'chicken', 'light dishes'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSID9N'
    },
    {
      name: 'Gavi di Gavi',
      type: 'white wine',
      description: '피에몬테의 우아한 화이트',
      tastingNotes: ['elegant', 'crisp', 'light'],
      image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=600&fit=crop',
      price: '₩48,000',
      foodPairings: ['seafood', 'salad', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIEtz'
    },
    {
      name: 'Meursault',
      type: 'white wine',
      description: '부르고뉴의 프리미엄 샤르도네',
      tastingNotes: ['rich', 'complex', 'heavy'],
      image: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&h=600&fit=crop',
      price: '₩180,000',
      foodPairings: ['seafood', 'chicken', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIEOU'
    },
    // 위스키 (20개)
    {
      name: 'Macallan 18 Year',
      type: 'whisky',
      description: '스코틀랜드의 명품 싱글몰트',
      tastingNotes: ['complex', 'smooth', 'elegant'],
      image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&h=600&fit=crop',
      price: '₩450,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIE5a'
    },
    {
      name: 'Glenfiddich 15 Year',
      type: 'whisky',
      description: '부드럽고 균형잡힌 싱글몰트',
      tastingNotes: ['smooth', 'fruity', 'elegant'],
      image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=600&fit=crop',
      price: '₩120,000',
      foodPairings: ['meat', 'cheese', 'nuts'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIFHd'
    },
    {
      name: 'Lagavulin 16 Year',
      type: 'whisky',
      description: '아일레이의 스모키한 위스키',
      tastingNotes: ['smoky', 'bold', 'complex'],
      image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=600&fit=crop',
      price: '₩150,000',
      foodPairings: ['meat', 'cheese', 'seafood'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIHo7'
    },
    {
      name: 'Yamazaki 12 Year',
      type: 'whisky',
      description: '일본의 섬세한 싱글몰트',
      tastingNotes: ['elegant', 'smooth', 'fruity'],
      image: 'https://images.unsplash.com/photo-1582818628682-e1a6c8a6bfe3?w=400&h=600&fit=crop',
      price: '₩280,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['solo-drinking', 'date'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIHKl'
    },
    {
      name: 'Hibiki Harmony',
      type: 'whisky',
      description: '일본의 조화로운 블렌디드',
      tastingNotes: ['smooth', 'elegant', 'complex'],
      image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=600&fit=crop',
      price: '₩180,000',
      foodPairings: ['meat', 'cheese', 'dessert'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIH3d'
    },
    {
      name: 'Johnnie Walker Blue Label',
      type: 'whisky',
      description: '최고급 블렌디드 스카치',
      tastingNotes: ['complex', 'smooth', 'elegant'],
      image: 'https://images.unsplash.com/photo-1504279807252-e1d6e5f0a9b5?w=400&h=600&fit=crop',
      price: '₩350,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIIma'
    },
    {
      name: 'Talisker 10 Year',
      type: 'whisky',
      description: '스카이 섬의 해양 위스키',
      tastingNotes: ['smoky', 'spicy', 'bold'],
      image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=600&fit=crop',
      price: '₩95,000',
      foodPairings: ['meat', 'seafood', 'cheese'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIIEg'
    },
    {
      name: 'Highland Park 12 Year',
      type: 'whisky',
      description: '오크니의 균형잡힌 위스키',
      tastingNotes: ['smooth', 'smoky', 'elegant'],
      image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&h=600&fit=crop',
      price: '₩110,000',
      foodPairings: ['meat', 'cheese', 'nuts'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIITm'
    },
    {
      name: 'Ardbeg 10 Year',
      type: 'whisky',
      description: '아일레이의 강렬한 피트',
      tastingNotes: ['smoky', 'bold', 'complex'],
      image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=600&fit=crop',
      price: '₩125,000',
      foodPairings: ['meat', 'cheese', 'seafood'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIJdP'
    },
    {
      name: 'Glenmorangie 18 Year',
      type: 'whisky',
      description: '하이랜드의 우아한 위스키',
      tastingNotes: ['elegant', 'smooth', 'fruity'],
      image: 'https://images.unsplash.com/photo-1582818628682-e1a6c8a6bfe3?w=400&h=600&fit=crop',
      price: '₩220,000',
      foodPairings: ['meat', 'cheese', 'dessert'],
      occasions: ['solo-drinking', 'date'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIJBq'
    },
    {
      name: 'Maker\'s Mark',
      type: 'whisky',
      description: '부드러운 켄터키 버번',
      tastingNotes: ['sweet', 'smooth', 'rich'],
      image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=600&fit=crop',
      price: '₩65,000',
      foodPairings: ['meat', 'bbq', 'dessert'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIJZe'
    },
    {
      name: 'Woodford Reserve',
      type: 'whisky',
      description: '프리미엄 켄터키 버번',
      tastingNotes: ['rich', 'smooth', 'complex'],
      image: 'https://images.unsplash.com/photo-1504279807252-e1d6e5f0a9b5?w=400&h=600&fit=crop',
      price: '₩85,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIKu5'
    },
    {
      name: 'Buffalo Trace',
      type: 'whisky',
      description: '가성비 좋은 버번',
      tastingNotes: ['smooth', 'sweet', 'rich'],
      image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=600&fit=crop',
      price: '₩55,000',
      foodPairings: ['meat', 'bbq', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIKOJ'
    },
    {
      name: 'Jack Daniel\'s Single Barrel',
      type: 'whisky',
      description: '테네시의 프리미엄 위스키',
      tastingNotes: ['smooth', 'rich', 'bold'],
      image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&h=600&fit=crop',
      price: '₩95,000',
      foodPairings: ['meat', 'bbq', 'cheese'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSILb2'
    },
    {
      name: 'Crown Royal Reserve',
      type: 'whisky',
      description: '캐나다의 부드러운 위스키',
      tastingNotes: ['smooth', 'elegant', 'light'],
      image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=600&fit=crop',
      price: '₩75,000',
      foodPairings: ['meat', 'cheese', 'dessert'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSILIb'
    },
    {
      name: 'Jameson Black Barrel',
      type: 'whisky',
      description: '아일랜드의 부드러운 위스키',
      tastingNotes: ['smooth', 'fruity', 'light'],
      image: 'https://images.unsplash.com/photo-1582818628682-e1a6c8a6bfe3?w=400&h=600&fit=crop',
      price: '₩68,000',
      foodPairings: ['meat', 'cheese', 'dessert'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIMeL'
    },
    {
      name: 'Redbreast 12 Year',
      type: 'whisky',
      description: '아일랜드의 싱글 팟 스틸',
      tastingNotes: ['rich', 'spicy', 'complex'],
      image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=600&fit=crop',
      price: '₩120,000',
      foodPairings: ['meat', 'cheese', 'nuts'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIMua'
    },
    {
      name: 'Nikka From The Barrel',
      type: 'whisky',
      description: '일본의 강렬한 블렌디드',
      tastingNotes: ['bold', 'rich', 'complex'],
      image: 'https://images.unsplash.com/photo-1504279807252-e1d6e5f0a9b5?w=400&h=600&fit=crop',
      price: '₩95,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSIMZA'
    },
    {
      name: 'Balvenie 14 Year Caribbean Cask',
      type: 'whisky',
      description: '럼 캐스크 피니시 위스키',
      tastingNotes: ['sweet', 'fruity', 'smooth'],
      image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=600&fit=crop',
      price: '₩180,000',
      foodPairings: ['meat', 'cheese', 'dessert'],
      occasions: ['solo-drinking', 'date'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSINiG'
    },
    {
      name: 'Oban 14 Year',
      type: 'whisky',
      description: '서부 하이랜드의 균형잡힌 위스키',
      tastingNotes: ['smooth', 'elegant', 'complex'],
      image: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=400&h=600&fit=crop',
      price: '₩145,000',
      foodPairings: ['meat', 'seafood', 'cheese'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSINB6'
    },
    // 칵테일 (15개)
    {
      name: 'Mojito',
      type: 'cocktail',
      description: '상큼한 민트와 라임의 조화',
      tastingNotes: ['fresh', 'light', 'fruity'],
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=600&fit=crop',
      price: '₩15,000',
      foodPairings: ['seafood', 'light dishes', 'spicy'],
      occasions: ['date', 'gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIN5c'
    },
    {
      name: 'Margarita',
      type: 'cocktail',
      description: '상큼한 라임과 테킬라',
      tastingNotes: ['crisp', 'fruity', 'light'],
      image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=600&fit=crop',
      price: '₩14,000',
      foodPairings: ['spicy', 'seafood', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIOnv'
    },
    {
      name: 'Old Fashioned',
      type: 'cocktail',
      description: '클래식하고 우아한 위스키 칵테일',
      tastingNotes: ['bold', 'smooth', 'elegant'],
      image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400&h=600&fit=crop',
      price: '₩16,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIOGI'
    },
    {
      name: 'Negroni',
      type: 'cocktail',
      description: '이탈리아의 쌉싸름한 칵테일',
      tastingNotes: ['bitter', 'bold', 'complex'],
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=400&h=600&fit=crop',
      price: '₩15,000',
      foodPairings: ['cheese', 'meat', 'nuts'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIOUw'
    },
    {
      name: 'Espresso Martini',
      type: 'cocktail',
      description: '커피와 보드카의 만남',
      tastingNotes: ['rich', 'bold', 'smooth'],
      image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=600&fit=crop',
      price: '₩17,000',
      foodPairings: ['dessert', 'chocolate', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIPlf'
    },
    {
      name: 'Aperol Spritz',
      type: 'cocktail',
      description: '이탈리아의 상쾌한 아페리티프',
      tastingNotes: ['light', 'fruity', 'fresh'],
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=600&fit=crop',
      price: '₩13,000',
      foodPairings: ['light dishes', 'cheese', 'seafood'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIPOn'
    },
    {
      name: 'Manhattan',
      type: 'cocktail',
      description: '뉴욕의 클래식 칵테일',
      tastingNotes: ['smooth', 'elegant', 'bold'],
      image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400&h=600&fit=crop',
      price: '₩16,000',
      foodPairings: ['meat', 'cheese', 'chocolate'],
      occasions: ['solo-drinking', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIP5H'
    },
    {
      name: 'Cosmopolitan',
      type: 'cocktail',
      description: '세련된 핑크빛 칵테일',
      tastingNotes: ['fruity', 'elegant', 'light'],
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=400&h=600&fit=crop',
      price: '₩15,000',
      foodPairings: ['light dishes', 'seafood', 'dessert'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIQoy'
    },
    {
      name: 'Whiskey Sour',
      type: 'cocktail',
      description: '새콤달콤한 위스키 칵테일',
      tastingNotes: ['fruity', 'smooth', 'light'],
      image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=600&fit=crop',
      price: '₩14,000',
      foodPairings: ['meat', 'cheese', 'light dishes'],
      occasions: ['gathering', 'solo-drinking'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIQLZ'
    },
    {
      name: 'Daiquiri',
      type: 'cocktail',
      description: '쿠바의 클래식 럼 칵테일',
      tastingNotes: ['fresh', 'fruity', 'light'],
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=600&fit=crop',
      price: '₩13,000',
      foodPairings: ['seafood', 'light dishes', 'dessert'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIQ0d'
    },
    {
      name: 'Gin & Tonic',
      type: 'cocktail',
      description: '상쾌한 진과 토닉의 조합',
      tastingNotes: ['crisp', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400&h=600&fit=crop',
      price: '₩12,000',
      foodPairings: ['seafood', 'light dishes', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIRjT'
    },
    {
      name: 'Moscow Mule',
      type: 'cocktail',
      description: '생강과 보드카의 상쾌한 조합',
      tastingNotes: ['spicy', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1536935338788-846bb9981813?w=400&h=600&fit=crop',
      price: '₩13,000',
      foodPairings: ['spicy', 'seafood', 'light dishes'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIRyh'
    },
    {
      name: 'Piña Colada',
      type: 'cocktail',
      description: '열대의 달콤한 칵테일',
      tastingNotes: ['sweet', 'fruity', 'rich'],
      image: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=400&h=600&fit=crop',
      price: '₩15,000',
      foodPairings: ['dessert', 'seafood', 'light dishes'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIRLr'
    },
    {
      name: 'Bloody Mary',
      type: 'cocktail',
      description: '토마토 베이스의 세이보리 칵테일',
      tastingNotes: ['spicy', 'savory', 'bold'],
      image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&h=600&fit=crop',
      price: '₩14,000',
      foodPairings: ['brunch', 'seafood', 'spicy'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sour', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSIR1C'
    },
    {
      name: 'Mai Tai',
      type: 'cocktail',
      description: '폴리네시안 스타일의 럼 칵테일',
      tastingNotes: ['fruity', 'tropical', 'medium'],
      image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=400&h=600&fit=crop',
      price: '₩16,000',
      foodPairings: ['seafood', 'spicy', 'dessert'],
      occasions: ['date', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSISkw'
    },
    // 차 (10개)
    {
      name: 'Oolong Tea Premium',
      type: 'tea',
      description: '깊은 맛과 우아한 향의 우롱차',
      tastingNotes: ['floral', 'smooth', 'elegant'],
      image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=600&fit=crop',
      price: '₩12,000',
      foodPairings: ['meat', 'fish', 'cheese', 'dessert'],
      occasions: ['date', 'gathering', 'solo-meal'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSISDC'
    },
    {
      name: 'Matcha Green Tea',
      type: 'tea',
      description: '일본의 전통 말차',
      tastingNotes: ['rich', 'smooth', 'grassy'],
      image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=600&fit=crop',
      price: '₩15,000',
      foodPairings: ['dessert', 'light dishes', 'vegetable'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSISUJ'
    },
    {
      name: 'Earl Grey',
      type: 'tea',
      description: '베르가못 향의 클래식 홍차',
      tastingNotes: ['floral', 'elegant', 'smooth'],
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['dessert', 'cheese', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSITaD'
    },
    {
      name: 'Jasmine Tea',
      type: 'tea',
      description: '자스민 꽃향의 녹차',
      tastingNotes: ['floral', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=600&fit=crop',
      price: '₩9,000',
      foodPairings: ['seafood', 'light dishes', 'dessert'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSITmE'
    },
    {
      name: 'Pu-erh Tea Aged',
      type: 'tea',
      description: '숙성된 중국 흑차',
      tastingNotes: ['earthy', 'rich', 'smooth'],
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=600&fit=crop',
      price: '₩18,000',
      foodPairings: ['meat', 'cheese', 'heavy dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSITBK'
    },
    {
      name: 'Darjeeling First Flush',
      type: 'tea',
      description: '히말라야의 샴페인 티',
      tastingNotes: ['floral', 'light', 'elegant'],
      image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=600&fit=crop',
      price: '₩14,000',
      foodPairings: ['light dishes', 'dessert', 'cheese'],
      occasions: ['solo-meal', 'date'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSITQr'
    },
    {
      name: 'Sencha Green Tea',
      type: 'tea',
      description: '일본의 대표 녹차',
      tastingNotes: ['fresh', 'grassy', 'light'],
      image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=600&fit=crop',
      price: '₩10,000',
      foodPairings: ['seafood', 'vegetable', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIT6B'
    },
    {
      name: 'Chamomile Tea',
      type: 'tea',
      description: '편안한 허브티',
      tastingNotes: ['floral', 'light', 'soothing'],
      image: 'https://images.unsplash.com/photo-1597318281699-33b0c7d6c8b6?w=400&h=600&fit=crop',
      price: '₩7,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIUm5'
    },
    {
      name: 'Rooibos Tea',
      type: 'tea',
      description: '남아공의 카페인 프리 차',
      tastingNotes: ['sweet', 'smooth', 'light'],
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['dessert', 'light dishes', 'cheese'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIUHi'
    },
    {
      name: 'White Peony Tea',
      type: 'tea',
      description: '섬세한 중국 백차',
      tastingNotes: ['delicate', 'light', 'elegant'],
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=600&fit=crop',
      price: '₩16,000',
      foodPairings: ['light dishes', 'dessert', 'seafood'],
      occasions: ['solo-meal', 'date'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIUVF'
    },
    // 비알콜 (10개)
    {
      name: 'San Pellegrino Sparkling Water',
      type: 'non-alcoholic',
      description: '이탈리아의 프리미엄 탄산수',
      tastingNotes: ['light', 'fresh', 'clean'],
      image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400&h=600&fit=crop',
      price: '₩5,000',
      foodPairings: ['all'],
      occasions: ['all'],
      tastes: ['light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIVg7'
    },
    {
      name: 'Fever-Tree Ginger Beer',
      type: 'non-alcoholic',
      description: '프리미엄 진저 비어',
      tastingNotes: ['spicy', 'fresh', 'bold'],
      image: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400&h=600&fit=crop',
      price: '₩7,000',
      foodPairings: ['spicy', 'meat', 'seafood'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIVDo'
    },
    {
      name: 'Kombucha Original',
      type: 'non-alcoholic',
      description: '발효 차 음료',
      tastingNotes: ['tangy', 'light', 'fresh'],
      image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['light dishes', 'vegetable', 'seafood'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIVRz'
    },
    {
      name: 'Cold Pressed Green Juice',
      type: 'non-alcoholic',
      description: '신선한 채소 주스',
      tastingNotes: ['fresh', 'healthy', 'light'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩12,000',
      foodPairings: ['light dishes', 'salad'],
      occasions: ['solo-meal'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIV7D'
    },
    {
      name: 'Fresh Orange Juice',
      type: 'non-alcoholic',
      description: '갓 짜낸 오렌지 주스',
      tastingNotes: ['fruity', 'sweet', 'fresh'],
      image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=600&fit=crop',
      price: '₩9,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIWo8'
    },
    {
      name: 'Elderflower Cordial',
      type: 'non-alcoholic',
      description: '엘더플라워 시럽 음료',
      tastingNotes: ['floral', 'sweet', 'light'],
      image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['light dishes', 'dessert', 'cheese'],
      occasions: ['gathering', 'date'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIWDO'
    },
    {
      name: 'Virgin Mojito',
      type: 'non-alcoholic',
      description: '무알콜 모히또',
      tastingNotes: ['fresh', 'minty', 'light'],
      image: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400&h=600&fit=crop',
      price: '₩10,000',
      foodPairings: ['seafood', 'light dishes', 'spicy'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIWUl'
    },
    {
      name: 'Seedlip Garden Non-Alcoholic Spirit',
      type: 'non-alcoholic',
      description: '프리미엄 무알콜 스피릿',
      tastingNotes: ['herbal', 'complex', 'light'],
      image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=600&fit=crop',
      price: '₩15,000',
      foodPairings: ['light dishes', 'seafood', 'cheese'],
      occasions: ['date', 'gathering'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIXaa'
    },
    {
      name: 'Coconut Water',
      type: 'non-alcoholic',
      description: '천연 코코넛 워터',
      tastingNotes: ['fresh', 'light', 'natural'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩6,000',
      foodPairings: ['light dishes', 'seafood'],
      occasions: ['solo-meal', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIXqy'
    },
    {
      name: 'Artisan Lemonade',
      type: 'non-alcoholic',
      description: '수제 레모네이드',
      tastingNotes: ['tangy', 'sweet', 'fresh'],
      image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['light dishes', 'dessert', 'spicy'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIX3j'
    },
    {
      name: 'Perrier Sparkling Water',
      type: 'non-alcoholic',
      description: '프랑스의 천연 탄산수',
      tastingNotes: ['crisp', 'clean', 'light'],
      image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400&h=600&fit=crop',
      price: '₩4,500',
      foodPairings: ['all'],
      occasions: ['all'],
      tastes: ['light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIYim'
    },
    {
      name: 'Tonic Water Premium',
      type: 'non-alcoholic',
      description: '프리미엄 토닉 워터',
      tastingNotes: ['bitter', 'crisp', 'light'],
      image: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400&h=600&fit=crop',
      price: '₩6,000',
      foodPairings: ['light dishes', 'seafood'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIYCa'
    },
    {
      name: 'Ginger Ale Premium',
      type: 'non-alcoholic',
      description: '프리미엄 진저 에일',
      tastingNotes: ['spicy', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=600&fit=crop',
      price: '₩6,500',
      foodPairings: ['spicy', 'meat', 'seafood'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIYTt'
    },
    {
      name: 'Cranberry Juice',
      type: 'non-alcoholic',
      description: '상큼한 크랜베리 주스',
      tastingNotes: ['tart', 'fruity', 'fresh'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['light dishes', 'dessert'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIY5H'
    },
    {
      name: 'Apple Cider Non-Alcoholic',
      type: 'non-alcoholic',
      description: '무알콜 애플 사이다',
      tastingNotes: ['fruity', 'sweet', 'fresh'],
      image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=600&fit=crop',
      price: '₩7,000',
      foodPairings: ['dessert', 'light dishes', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIZnP'
    },
    {
      name: 'Pomegranate Juice',
      type: 'non-alcoholic',
      description: '석류 주스',
      tastingNotes: ['rich', 'fruity', 'sweet'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩10,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIZAn'
    },
    {
      name: 'Aloe Vera Drink',
      type: 'non-alcoholic',
      description: '알로에 베라 음료',
      tastingNotes: ['fresh', 'light', 'soothing'],
      image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=400&h=600&fit=crop',
      price: '₩5,500',
      foodPairings: ['light dishes', 'dessert'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIZOu'
    },
    {
      name: 'Sparkling Apple Juice',
      type: 'non-alcoholic',
      description: '스파클링 애플 주스',
      tastingNotes: ['fruity', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=400&h=600&fit=crop',
      price: '₩7,500',
      foodPairings: ['dessert', 'light dishes', 'cheese'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSIZ08'
    },
    {
      name: 'Peach Iced Tea',
      type: 'non-alcoholic',
      description: '복숭아 아이스티',
      tastingNotes: ['fruity', 'sweet', 'refreshing'],
      image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400&h=600&fit=crop',
      price: '₩6,500',
      foodPairings: ['light dishes', 'dessert'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI0bH'
    },
    {
      name: 'Lemon Iced Tea',
      type: 'non-alcoholic',
      description: '레몬 아이스티',
      tastingNotes: ['citrus', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=600&fit=crop',
      price: '₩6,000',
      foodPairings: ['light dishes', 'seafood'],
      occasions: ['gathering', 'camping'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI0pu'
    },
    {
      name: 'Mango Lassi',
      type: 'non-alcoholic',
      description: '인도의 망고 요거트 음료',
      tastingNotes: ['creamy', 'fruity', 'rich'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩8,500',
      foodPairings: ['spicy', 'dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSI0C7'
    },
    {
      name: 'Watermelon Juice',
      type: 'non-alcoholic',
      description: '수박 주스',
      tastingNotes: ['fresh', 'sweet', 'light'],
      image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['light dishes', 'dessert'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI0T5'
    },
    {
      name: 'Pineapple Juice',
      type: 'non-alcoholic',
      description: '파인애플 주스',
      tastingNotes: ['tropical', 'sweet', 'tangy'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩8,500',
      foodPairings: ['seafood', 'spicy', 'dessert'],
      occasions: ['gathering', 'camping'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI1ak'
    },
    {
      name: 'Grapefruit Juice',
      type: 'non-alcoholic',
      description: '자몽 주스',
      tastingNotes: ['bitter', 'citrus', 'fresh'],
      image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['light dishes', 'seafood'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI1sh'
    },
    {
      name: 'Strawberry Smoothie',
      type: 'non-alcoholic',
      description: '딸기 스무디',
      tastingNotes: ['fruity', 'creamy', 'sweet'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩9,500',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSI1HE'
    },
    {
      name: 'Green Smoothie',
      type: 'non-alcoholic',
      description: '그린 스무디',
      tastingNotes: ['healthy', 'fresh', 'light'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩11,000',
      foodPairings: ['light dishes', 'salad'],
      occasions: ['solo-meal'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI1Vm'
    },
    {
      name: 'Berry Mix Smoothie',
      type: 'non-alcoholic',
      description: '베리 믹스 스무디',
      tastingNotes: ['fruity', 'rich', 'sweet'],
      image: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400&h=600&fit=crop',
      price: '₩10,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSI3OJ'
    },
    {
      name: 'Iced Americano',
      type: 'non-alcoholic',
      description: '아이스 아메리카노',
      tastingNotes: ['bold', 'bitter', 'refreshing'],
      image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=600&fit=crop',
      price: '₩5,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI34x'
    },
    {
      name: 'Iced Latte',
      type: 'non-alcoholic',
      description: '아이스 라떼',
      tastingNotes: ['creamy', 'smooth', 'mild'],
      image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=600&fit=crop',
      price: '₩6,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI4hG'
    },
    {
      name: 'Cold Brew Coffee',
      type: 'non-alcoholic',
      description: '콜드브루 커피',
      tastingNotes: ['smooth', 'rich', 'bold'],
      image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=600&fit=crop',
      price: '₩6,500',
      foodPairings: ['dessert', 'chocolate'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSI4tF'
    },
    // 차 추가 (20개 더)
    {
      name: 'Assam Black Tea',
      type: 'tea',
      description: '인도의 진한 홍차',
      tastingNotes: ['bold', 'malty', 'rich'],
      image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=600&fit=crop',
      price: '₩9,000',
      foodPairings: ['dessert', 'cheese', 'meat'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSI8tu'
    },
    {
      name: 'Ceylon Tea',
      type: 'tea',
      description: '스리랑카의 향긋한 홍차',
      tastingNotes: ['bright', 'citrus', 'light'],
      image: 'https://images.unsplash.com/photo-1597318281699-33b0c7d6c8b6?w=400&h=600&fit=crop',
      price: '₩8,500',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI8Xe'
    },
    {
      name: 'English Breakfast Tea',
      type: 'tea',
      description: '영국의 클래식 블렌드',
      tastingNotes: ['bold', 'rich', 'smooth'],
      image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=600&fit=crop',
      price: '₩7,500',
      foodPairings: ['dessert', 'cheese', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSI5co'
    },
    {
      name: 'Gyokuro Green Tea',
      type: 'tea',
      description: '일본 최고급 녹차',
      tastingNotes: ['umami', 'sweet', 'rich'],
      image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=600&fit=crop',
      price: '₩20,000',
      foodPairings: ['seafood', 'light dishes', 'dessert'],
      occasions: ['solo-meal', 'date'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSI9TB'
    },
    {
      name: 'Hojicha Roasted Tea',
      type: 'tea',
      description: '일본의 볶은 녹차',
      tastingNotes: ['roasted', 'smooth', 'light'],
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=600&fit=crop',
      price: '₩9,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJabN'
    },
    {
      name: 'Genmaicha Brown Rice Tea',
      type: 'tea',
      description: '현미차 블렌드 녹차',
      tastingNotes: ['nutty', 'toasted', 'light'],
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['light dishes', 'seafood', 'vegetable'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJaxf'
    },
    {
      name: 'Longjing Dragon Well Tea',
      type: 'tea',
      description: '중국의 명품 녹차',
      tastingNotes: ['delicate', 'sweet', 'elegant'],
      image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400&h=600&fit=crop',
      price: '₩18,000',
      foodPairings: ['seafood', 'light dishes', 'dessert'],
      occasions: ['solo-meal', 'date'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJa0t'
    },
    {
      name: 'Tie Guan Yin Oolong',
      type: 'tea',
      description: '철관음 우롱차',
      tastingNotes: ['floral', 'complex', 'elegant'],
      image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=600&fit=crop',
      price: '₩15,000',
      foodPairings: ['meat', 'seafood', 'cheese'],
      occasions: ['solo-meal', 'date'],
      tastes: ['sweet', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSJbob'
    },
    {
      name: 'Da Hong Pao Rock Tea',
      type: 'tea',
      description: '대홍포 암차',
      tastingNotes: ['rich', 'mineral', 'complex'],
      image: 'https://images.unsplash.com/photo-1597318281699-33b0c7d6c8b6?w=400&h=600&fit=crop',
      price: '₩22,000',
      foodPairings: ['meat', 'cheese', 'heavy dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'heavy'],
      purchaseUrl: 'https://link.coupang.com/a/dSJbEZ'
    },
    {
      name: 'Lapsang Souchong',
      type: 'tea',
      description: '훈연 홍차',
      tastingNotes: ['smoky', 'bold', 'unique'],
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=600&fit=crop',
      price: '₩11,000',
      foodPairings: ['meat', 'cheese', 'heavy dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: 'https://link.coupang.com/a/dSJb3T'
    },
    {
      name: 'Silver Needle White Tea',
      type: 'tea',
      description: '백호은침 백차',
      tastingNotes: ['delicate', 'sweet', 'elegant'],
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=600&fit=crop',
      price: '₩19,000',
      foodPairings: ['light dishes', 'seafood', 'dessert'],
      occasions: ['solo-meal', 'date'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJcoh'
    },
    {
      name: 'Mint Tea Moroccan',
      type: 'tea',
      description: '모로코 민트 티',
      tastingNotes: ['fresh', 'minty', 'sweet'],
      image: 'https://images.unsplash.com/photo-1597318281699-33b0c7d6c8b6?w=400&h=600&fit=crop',
      price: '₩7,500',
      foodPairings: ['spicy', 'light dishes', 'dessert'],
      occasions: ['gathering', 'solo-meal'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJcPC'
    },
    {
      name: 'Hibiscus Tea',
      type: 'tea',
      description: '히비스커스 허브티',
      tastingNotes: ['tart', 'fruity', 'refreshing'],
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=600&fit=crop',
      price: '₩7,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sour', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSI7X0'
    },
    {
      name: 'Lavender Tea',
      type: 'tea',
      description: 'ㅁ',
      tastingNotes: ['floral', 'soothing', 'light'],
      image: 'https://images.unsplash.com/photo-1597318281699-33b0c7d6c8b6?w=400&h=600&fit=crop',
      price: '₩8,000',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJdfb'
    },
    {
      name: 'Peppermint Tea',
      type: 'tea',
      description: '페퍼민트 허브티',
      tastingNotes: ['fresh', 'minty', 'cooling'],
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=600&fit=crop',
      price: '₩6,500',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJdub'
    },
    {
      name: 'Ginger Turmeric Tea',
      type: 'tea',
      description: '생강 강황 차',
      tastingNotes: ['spicy', 'warming', 'earthy'],
      image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=400&h=600&fit=crop',
      price: '₩8,500',
      foodPairings: ['spicy', 'light dishes'],
      occasions: ['solo-meal'],
      tastes: ['bitter', 'medium'],
      purchaseUrl: ''
    },
    {
      name: 'Rose Tea',
      type: 'tea',
      description: '장미 꽃차',
      tastingNotes: ['floral', 'elegant', 'light'],
      image: 'https://images.unsplash.com/photo-1597318281699-33b0c7d6c8b6?w=400&h=600&fit=crop',
      price: '₩9,500',
      foodPairings: ['dessert', 'light dishes'],
      occasions: ['solo-meal', 'date'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJdKJ'
    },
    {
      name: 'Chrysanthemum Tea',
      type: 'tea',
      description: '국화차',
      tastingNotes: ['floral', 'light', 'soothing'],
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=600&fit=crop',
      price: '₩7,500',
      foodPairings: ['light dishes', 'dessert'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJdYT'
    },
    {
      name: 'Barley Tea Korean',
      type: 'tea',
      description: '보리차',
      tastingNotes: ['nutty', 'light', 'refreshing'],
      image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400&h=600&fit=crop',
      price: '₩5,000',
      foodPairings: ['all'],
      occasions: ['all'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJeca'
    },
    {
      name: 'Corn Silk Tea',
      type: 'tea',
      description: '옥수수수염차',
      tastingNotes: ['sweet', 'light', 'soothing'],
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=600&fit=crop',
      price: '₩5,500',
      foodPairings: ['light dishes', 'dessert'],
      occasions: ['solo-meal', 'gathering'],
      tastes: ['sweet', 'light'],
      purchaseUrl: 'https://link.coupang.com/a/dSJeqj'
    },
  ];

  for (const drink of drinks) {
    await prisma.drink.create({
      data: drink,
    });
  }

  console.log(`✅ Created ${drinks.length} drinks`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
